### ISSUE TITLE
Cant find value in cloud config

### ISSUE THREAD

**Issue by ykutovoy** [cloud-py-api/mediadc#35] opened 2021-12-23 11:35 UTC
**Screenshot**
![image](https://user-images.githubusercontent.com/13015154/147230501-546ded41-ba5f-4bb4-a18d-17eca2dd5b98.png)

**Describe the bug**
After installing application getting this kind of errors.

Looks like app try to find config in some kind default location

**Desktop (please complete the following information):**
 - OS Description:    Ubuntu 20.04.3 LTS
 - CPU:  Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (2 cores)
 - Browser: any
 - Nextcloud version: 22.2.3
 - Database configuration: mysql 10.3.32 206,2 MB
 - Python version: 3.8.10 (default, Nov 26 2021)
 - MediaDC version: 0.1.8

**Additional context**
Could You add textbox in configuration section to point to config file manually, in case if app cannot find it by itself?

Where can i write correct path (file/variable)? to make tests.

**Comment by bigcat88** [comment] 2021-12-23 11:49
@ykutovoy 
In future versions(probably 0.2.0, we are currently working on that technique) there will be no such things as reads from config at all.
In current versions we dont read from config directly, we call nextcloud's `occ` to do that. 
Can you post here what `occ` return for that?
`sudo -u www-data php /pathtonextcloufdoler/occ config:system:get datadirectory`
if nextcloud is in /var/www then command will be something like that:
`sudo -u www-data php /var/www/nextcloud/occ config:system:get datadirectory`

**Comment by ykutovoy** [comment] 2021-12-23 12:19
For sure:
```
sudo -u www-data php --define apc.enable_cli=1 /var/www/html/cloud/occ config:system:get datadirectory
/media/oc_data/owncloud_data/
```

You can see that i've used inline definition **--define apc.enable_cli=1**
it is an issue for other app (face recognition) which conflicts with this definition

without this it drops like this:
```
sudo -u www-data php /var/www/html/cloud/occ config:system:get datadirectory
[sudo] password for *****:
An unhandled exception has been thrown:
OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```

**Comment by ykutovoy** [comment] 2021-12-23 12:22
I'm ready to add path directly to file, if You will say where :)
Wile we waiting for the next release.

**Comment by bigcat88** [comment] 2021-12-23 12:56
> For sure:
> 
> ```
> sudo -u www-data php --define apc.enable_cli=1 /var/www/html/cloud/occ config:system:get datadirectory
> /media/oc_data/owncloud_data/
> ```
> 
> You can see that i've used inline definition **--define apc.enable_cli=1** it is an issue for other app (face recognition) which conflicts with this definition
> 
> without this it drops like this:
> 
> ```
> sudo -u www-data php /var/www/html/cloud/occ config:system:get datadirectory
> [sudo] password for *****:
> An unhandled exception has been thrown:
> OC\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
> ```

So you have partially broken NC instance(`occ` is a official tool) and ask why our app is no working =)
We will not fix this, when we will go away from use `occ` a, your problem will bee solved.

You can change file `occ_cloud.py`, line 87. This is code that call's `occ`. 
Change `success, result = php_call(OCC, '--no-warnings', occ_task, *params, decode=decode)`
to
`success, result = php_call('--define', 'apc.enable_cli=1', OCC, '--no-warnings', occ_task, *params, decode=decode)`

**Comment by ykutovoy** [comment] 2021-12-23 13:20
<img width="302" alt="image" src="https://user-images.githubusercontent.com/13015154/147245942-efe5fd7d-b6ab-4582-9cbe-281d2cc93752.png">

Thank You now it works
unfortunately I'm just a USER (may be a bit advanced) :)

If it will be interesting for anybody, I can try to find that issue...
at the moment Yours app works perfect

**Comment by bigcat88** [comment] 2022-02-01 13:44
@dagguh for snap users it a bit different situation,  it much more complex. we will start to support snap installations from 0.2.0 or 0.2.2 version, just be give us time.

**Comment by 2br-2b** [comment] 2022-02-02 22:27
I can confirm. I have NC installed via Snap and I have the same issue. Looking forward to sorting out the 150+ gb of files in my photos!

**Comment by bigcat88** [comment] 2022-12-04 10:20
@2br-2b and others.
If you are still using snap please try beta version. #91

**Comment by 2br-2b** [comment] 2022-12-07 00:59
Per https://github.com/andrey18106/mediadc/issues/91#issuecomment-1340225944, it seems that we'll have to wait until NC25 is released to test out the beta unless anyone wants to update from Git.

**Comment by andrey18106** [comment] 2023-01-31 20:16
Since MediaDC 0.3.0 version Configuration page removed with pre-compiled binaries added this issue is not actual. Closing as resolved.

If have any relates questions feel free to open a new issue in [cloud_py_api](https://github.com/cloud-py-api/cloud_py_api) as this part moved there.

**Closed by andrey18106** 2023-01-31 20:16 UTC
Labels: solution
